name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"

env:
  VLC_HASH: 5e70837d8d766db6ca5052a2d4f503ad37243d9c # 3.0.16

jobs:
  actionlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
  build-macos:
    needs: [actionlint]

    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
        include:
          - target: x86_64
            os: macos-latest
          - target: aarch64
            os: macos-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "videolan/vlc"
          ref: ${{ env.VLC_HASH }}
      - uses: actions/checkout@v2
        with:
          path: vlc-build
      - name: Prepare
        run: |
          patch -p1 < vlc-build/patches/patch_mac_build_arg.patch
          patch -p1 < vlc-build/patches/dump_aribsub.patch
          patch -p1 < vlc-build/patches/dump_pcr.patch
          patch -p1 < vlc-build/patches/dump_tot.patch
          patch -p1 < vlc-build/patches/patch_version.patch
          patch -p1 < vlc-build/patches/patch_user_agent.patch
          mkdir -p build
      - name: Prepare (aarch64)
        if: matrix.target == 'aarch64'
        run: |
          patch -p1 < vlc-build/patches/arm64.patch
          patch -p1 < vlc-build/patches/codesign.patch
      - name: Build
        run: |
          which msgmerge
          ../extras/package/macosx/build.sh -c -i n -a ${{ matrix.target }}
        working-directory: ./build
      - name: Check
        run: ls -la
        working-directory: ./build
      - name: Pack build artifact
        run: zip -rq build.zip ./build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-build-${{ matrix.target }}
          path: build.zip
      - name: Upload libaribsub artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-aribsub-dylib-${{ matrix.target }}
          path: build/vlc_install_dir/lib/vlc/plugins/codec/libaribsub_plugin.dylib
      - name: Upload libts artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-ts-dylib-${{ matrix.target }}
          path: build/vlc_install_dir/lib/vlc/plugins/demux/libts_plugin.dylib
      - name: Upload dmg artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-build-image-${{ matrix.target }}
          path: build/*.dmg

  build-windows:
    runs-on: ubuntu-latest

    needs: [actionlint]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "videolan/vlc"
          ref: ${{ env.VLC_HASH }}
      - uses: actions/checkout@v2
        with:
          path: vlc-build
      - name: Install build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install \
            gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64-tools \
            lua5.2 libtool automake autoconf autopoint make gettext pkg-config \
            wine64-development-tools libwine-dev \
            gperf
          sudo ln -sf /usr/include/wine/wine/* /usr/include/wine
      - name: Prepare
        run: |
          patch -p1 < vlc-build/patches/patch_mac_build_arg.patch
          patch -p1 < vlc-build/patches/dump_aribsub.patch
          patch -p1 < vlc-build/patches/dump_pcr.patch
          patch -p1 < vlc-build/patches/dump_tot.patch
          patch -p1 < vlc-build/patches/patch_version.patch
          patch -p1 < vlc-build/patches/patch_user_agent.patch
          mkdir -p build
      - name: Build
        run: |
          ../extras/package/win32/build.sh -z
        working-directory: ./build
      - name: Packaging
        run: |
          make package-win32-zip
        working-directory: ./build/win64
      - name: Check
        run: ls -la
        working-directory: ./build/win64
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            build/win64/vlc-3.0.16/*.txt
            build/win64/vlc-3.0.16/libvlc.dll
            build/win64/vlc-3.0.16/libvlccore.dll
            build/win64/vlc-3.0.16/plugins
